### ISSUE TITLE
Code Review for Santiago's GitHub Repository

### ISSUE THREAD

**Issue by RuriEnciso** [smunoz1988/Portfolio-mobile-first#6]
Great job, Santiago, on the progress you have made so far in your GitHub repository. We believe that you have the potential to produce an excellent product. To improve further, we recommend the following changes:  🤪🤪

-  Add Social Icons: 

It is suggested that you add the social icons to your website as they are in the Figma template. By doing so, your website will have better aesthetics and will be more user-friendly.

- Use SVG's instead of PNG's:

We recommend that you use SVG's instead of PNG's for your website. SVG's are vector graphics, which means that they scale to any size without losing quality. In contrast, PNG's are raster images that can become blurry when scaled. Low-quality images can result in lower rankings in SEO.

### Checklist:
To ensure that you have made the necessary changes, we suggest the following checklist:

- Have you added the social icons as per the Figma template?
- Have you replaced all PNG's with SVG's to ensure that the images are scalable without losing quality?
- Have you moved all CSS to a separate CSS file instead of mixing it with HTML?

**Conclusion:**

By implementing the above recommendations and going through the checklist, we believe that you can improve the aesthetics, functionality, and SEO ranking of your website. Keep up the good work!

**Comment by smunoz1988** [comment]
Done! thanks for the suggestions.
